article/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, about, detail, dashboard, addArticle, updateArticle, deleteArticle, articles

app_name = "article"

# http://127.0.0.1:8000/
urlpatterns = [
    path("create/", index, name="index1"),
    path("<int:id>", detail, name="detail"),
    path("deneme1", index, name="detail1"),
    path("deneme2", index, name="detail2"),
    path("deneme3", index, name="detail3"),
    path("dashboard/", dashboard, name="dashboard"),
    path("addarticle/", addArticle, name="addarticle"),
    path("article/<int:id>", detail, name="detail"),
    path("update/<int:id>", updateArticle, name="update"),
    path("delete/<int:id>", deleteArticle, name="delete"),
    path("", articles, name="articles"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article.views import index, about, detail
from .views import frontend, hakkimizda
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000
# http://127.0.0.1:8000/frontend/ sa sagfasfas
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("articles/", include("article.urls")),
    path("comments/", include("comment.urls")),
    path("user/", include("user.urls")),
    path("frontend/", frontend, name="frontend"),
    path('tinymce/', include('tinymce.urls')),
    path("hakkimizda/", hakkimizda, name="hakkimizda"),
]
# http://127.0.0.1:8000/user/register

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

# http://127.0.0.1:8000/user/register
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.loginUser, name="login"),
    path("logout/", views.logoutUser, name="logout"),
]

templates/includes/breadcrumb.html
{% load static %}
<!-- bredcrumb Area Start-->
<section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">

                </div>
            </div>
        </div>
    </div>
</section>
<!-- bredcrumb Area End -->

templates/includes/footer.html
{% load static %}
<!-- footer area start -->
<footer class="footer-area pd-top-100">
    <div class="footer-inner padding-top-100 padding-bottom-65">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget widget">
                        <div class="logo">
                            <img src="{% static 'assets/img/logo.png' %}" alt="img">
                        </div>
                        <ul class="contact_info_list">
                            <li class="single-info-item">
                                <img src="{% static 'assets/img/icon/location.png' %}" alt="icon">
                                <div class="details">
                                    4920 Trails End Road Ft United States, FL 33311
                                </div>
                            </li>
                            <li class="single-info-item">
                                <img src="{% static 'assets/img/icon/envelope.png' %}" alt="icon">
                                <div class="details">
                                    ordernow@foodka.com
                                </div>
                            </li>
                            <li class="single-info-item">
                                <img src="{% static 'assets/img/icon/phone.png' %}" alt="icon">
                                <div class="details">
                                    +997 509 153 849
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget widget widget_link">
                        <h4 class="widget-title">Hot Menu</h4>
                        <ul>
                            <li><a href="menu-list.html">Burger King Whopper</a></li>
                            <li><a href="menu-list.html">Five Guys Cheeseburger</a></li>
                            <li><a href="menu-list.html">KFC Original Recipe Chicken</a></li>
                            <li><a href="menu-list.html">Wendy's Frosty</a></li>
                            <li><a href="menu-list.html">McDonald's Happy Meal</a></li>
                            <li><a href="menu-list.html">Domino's Pepperoni Pizza</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget widget widget_link">
                        <h4 class="widget-title">Opening Hours</h4>
                        <ul>
                            <li>Monday : 09.00am-10.00pm</li>
                            <li>Tuesday : 09.00am-10.00pm</li>
                            <li>Wednesday : 09.00am-10.00pm</li>
                            <li>Thursday : 09.00am-10.00pm</li>
                            <li>Friday : 09.00am-10.00pm</li>
                            <li>Saturday & Sunday : <span>Closed</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget widget widget_instagram_feeds">
                        <h4 class="widget-title">Instagram Feeds</h4>
                        <ul>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/1.png' %}" alt="instagram"/></a></li>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/2.png' %}" alt="instagram"/></a></li>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/3.png' %}" alt="instagram"/></a></li>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/4.png' %}" alt="instagram"/></a></li>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/5.png' %}" alt="instagram"/></a></li>
                            <li><a href="#"><img src="{% static 'assets/img/instagram/6.png' %}" alt="instagram"/></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 text-md-start text-center">
                    <div class="copyright-area">
                        <p>© 2021 Foodka. All Rights Reserved by Themefie</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="social-area text-md-end text-center mt-md-0 mt-2">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                        <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer area end -->

templates/includes/navbar.html
{% load static %}

<!-- navbar start -->
<header class="navbar-area">
    <nav class="navbar navbar-expand-lg">
        <div class="container nav-container">
            <div class="responsive-mobile-menu">
                <button class="menu toggle-btn d-block d-lg-none" data-target="#themefie_main_menu"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-left"></span>
                    <span class="icon-right"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="themefie_main_menu">
                <ul class="navbar-nav menu-open">
                    <li class="current-menu-item">
                        <a href="{% url 'article:articles' %}">MAKALELER</span></a>
                    </li>
                    <li class="current-menu-item">
                        <a href="{% url 'hakkimizda' %}">HAKKIMIZDA</span></a>
                    </li>

                </ul>
            </div>
            <div class="logo">
                <a class="main-logo" href="{% url 'index' %}"><img src="{% static 'logo.png' %}" height="40px" width="100px"
                                                             alt="img"></a>
            </div>
            <div class="nav-right-part nav-right-part-mobile">
                <ul>
                    <li><a class="search" href="#"><i class="ri-search-line"></i></a>
                    </li>
                    <li class="phone-contact d-md-block d-none"><i class="ri-phone-fill float-start"></i>
                        +997 509 153 849
                    </li>
                    <li class="menu-cart"><a href="cart.html">CART <span>1</span></a></li>
                    <li>49.50 $</li>
                </ul>
            </div>
            <div class="nav-right-part nav-right-part-desktop">
                <ul>

                    {% if request.user.is_authenticated %}
                    <li class="current-menu-item">
                        <a href="{% url 'article:dashboard' %}">KONTROL PANELI</span></a>
                    </li>
                    <li class="current-menu-item">
                        <a href="{% url 'user:logout' %}">CIKIS YAP</span></a>
                    </li>
                    {% else %}
                    <li class="current-menu-item">
                        <a href="{% url 'user:register' %}">KAYIT OL</span></a>
                    </li>
                    <li class="current-menu-item">
                        <a href="{% url 'user:login' %}">GIRIS YAP</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- navbar end -->