article/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, about, detail, dashboard, addArticle, updateArticle, deleteArticle, articles

app_name = "article"

# http://127.0.0.1:8000/
urlpatterns = [
    path("create/", index, name="index1"),
    path("<int:id>", detail, name="detail"),
    path("deneme1", index, name="detail1"),
    path("deneme2", index, name="detail2"),
    path("deneme3", index, name="detail3"),
    path("dashboard/", dashboard, name="dashboard"),
    path("addarticle/", addArticle, name="addarticle"),
    path("article/<int:id>", detail, name="detail"),
    path("update/<int:id>", updateArticle, name="update"),
    path("delete/<int:id>", deleteArticle, name="delete"),
    path("", articles, name="articles"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article.views import index, about, detail
from .views import frontend, hakkimizda
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000
# http://127.0.0.1:8000/frontend/ sa sagfasfas
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("articles/", include("article.urls")),
    path("comments/", include("comment.urls")),
    path("user/", include("user.urls")),
    path("frontend/", frontend, name="frontend"),
    path('tinymce/', include('tinymce.urls')),
    path("hakkimizda/", hakkimizda, name="hakkimizda"),
]
# http://127.0.0.1:8000/user/register

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.contrib import admin
from django.urls import path

from .views import addComment

app_name = "comment"

# http://127.0.0.1:8000/comments/comment/2
urlpatterns = [
    path('comment/<int:article_id>', addComment, name="addComment"),
]

article/models.py
from django.db import models
# from ckeditor.fields import RichTextField
from tinymce import models as tinymce_models

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="yazar")
    title = models.CharField(max_length=50)
    # content = RichTextField()
    content = tinymce_models.HTMLField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank=True, null=True, verbose_name="Makaleye fotoğraf ekleyin")

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

article/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404

from article.forms import ArticleForm
from article.models import Article
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    context = {
        "numbers": ["elma", "armut", "kivi"]
    }
    return render(request, "index.html", context)


def about(request):
    return render(request, "about.html")


def detail(request, id):
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    context = {
        "article": article,
        "comments": comments
    }
    return render(request, "detail.html", context)


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale başarıyla oluşturuldu.")
        return redirect("article:dashboard")
    context = {
        "form": form
    }
    return render(request, "addArticle.html", context)


@login_required(login_url="user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale başarıyla güncellendi.")
        return redirect("article:dashboard")
    context = {
        "form": form
    }
    return render(request, "update.html", context)


@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()

    messages.success(request, "Makale başarıyla silindi.")
    return redirect("article:dashboard")


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(Q(title__contains=keyword) | Q(content__contains=keyword))
    else:
        articles = Article.objects.all()
    return render(request, "articles.html", {"articles": articles})



templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>Selamlar</p>
{% endblock body %}

templates/addArticle.html
{% extends "layout.html" %}
{% block body %}

{% include 'includes/breadcrumb.html' %}

{% load crispy_forms_tags %}
<div class="row mt-5 mb-5">
    <div class="col-md-6 offset-md-3">
        <h3>Add Article</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <hr>
            <button type="submit" class="btn btn-danger">Kaydet</button>
        </form>
    </div>
</div>
{% endblock %}

templates/articles.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<!-- bredcrumb Area Start-->
<section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">
                    <h3>Blog
                    </h3>
                    <h1>Food Blog</h1>
                    <nav aria-label="breadcrumb">

                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- bredcrumb Area End -->

<div class="row mt-3">
    <div class="col-lg-8 offset-2" style="text-align:center">

        <form action="" method="GET">
            {% csrf_token %}
            <input type="text" name="keyword" class="input-sm">
            <button type="submit" class="btn btn-danger">Ara</button>
            <hr>
        </form>
    </div>
</div>

{% if articles %}
{% for article in articles %}
<div class="row">
    <div class="col-lg-8 offset-2">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4" style="text-align:center">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h1 class="fw-bolder mb-1">{{ article.title }}</h1></a>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{ article.created_date }}</div>
                <!-- Author-->
                <p class="lead">{{ article.author }}</p>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <figure class="mb-4" style="text-align:center">
                <img class="img-fluid rounded" height="250px" width="250px" src="{{ article.article_image.url }}"
                                      alt="..."></figure>
            {% endif %}
            <!-- Post content-->
            <section class="mb-5" style="text-align:center">
                <div class="">
                    {{ article.content|safe|truncatewords:5 }}
                    <a href="{% url 'article:detail' article.id %}">read more</a>
                </div>
            </section>
        </article>
        <hr>
    </div>
</div>

{% endfor %}
{% else %}
<div class="row">
    <div class="col-lg-8 offset-2">
        <div class="alert alert-danger" role="alert">
            Makale bulunamadı
        </div>
    </div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}

{% include 'includes/breadcrumb.html' %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small> {{request.user.username}} </small>
</p>
<hr>
<a href="{% url 'article:addarticle' %}" class="btn btn-danger">Makale Ekle</a>
<hr>

{% if articles %}
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
    </tr>
    </thead>
    <tbody>
    {% for article in articles %}
    <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
        <td>{{article.author}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="{% url 'article:update' article.id %}" class="btn btn-warning">Güncelle</a></td>
        <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert alert-danger" role="alert">
  Henüz bir makaleniz bulunmuyor!..
</div>
{% endif %}
{% endblock %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
    <!-- bredcrumb Area Start-->
    <section class="breadcrumb-area">
        <div class="banner-bg-img"></div>
        <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
        <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 align-self-center">
                    <div class="banner-inner text-center">
                        <h3>Blog Details
                        </h3>
                        <h1>Food Blog</h1>
                        <nav aria-label="breadcrumb">
                            <ul class="breadcrumb">
                              <li class="breadcrumb-item"><a href="home.html">Home</a></li>
                              <li class="breadcrumb-item"><a href="blog.html">Blog</a></li>
                              <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- bredcrumb Area End -->

<div class="row">
    <div class="col-lg-8 offset-2">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                <h1 class="lead">{{article.author}}</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.created_date|date:"SHORT_DATE_FORMAT" }}</div>

            </header>
            <!-- Preview image figure-->
            <figure class="mb-4">
                {% if article.article_image %}
                <img class="img-fluid rounded" src="{{ article.article_image.url }}"
                     alt="...">
                {% endif %}
            </figure>
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">
                    {{ article.content|safe }}
                </p>
            </section>
        </article>
        <section class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <form class="mb-4" method="POST" action="{% url 'comment:addComment' article.id %}">
                        {% csrf_token %}
                        <div class="group">
                            <label for="">İsim:</label>
                            <input type="text" name="comment_author" class="form-control"
                                   placeholder="Lütfen isiminizi giriniz...">
                        </div>
                        <!-- Comment form-->
                        <div class="group">
                            <label for="">Yorum:</label>
                            <textarea name="comment_content" class="form-control" rows="3"
                                      placeholder=""></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger mt-1">Ekle</button>
                    </form>
                    <hr>
                    <h4>Yorumlar</h4>
                    <hr>
                    {% if comments %}
                    {% for comment in comments %}
                    <!-- Single comment-->
                    <div class="d-flex mt-3">
                        <div class="flex-shrink-0"><img class="rounded-circle"
                                                        src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="...">
                        </div>
                        <div class="ms-3">
                            <div class="fw-bold">{{ comment.comment_author }} <small>{{comment.comment_date}}</small></div>
                            {{ comment.comment_content }}
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="alert alert-danger">
                        Bu makaleye ait herhangi bir yorum bulunmuyor
                    </div>
                    {% endif %}
                </div>
            </div>
        </section>

    </div>

</div>

{% endblock %}

templates/hakkimizda.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

<!-- bredcrumb Area Start-->
<section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">
                    <h3>About us
                    </h3>
                    <h1>Who are we?</h1>
                    <nav aria-label="breadcrumb">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="home-1.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- bredcrumb Area End -->

<!-- about Area Start-->
<section class="about-area pd-top-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-sm-8">
                <div class="thumb mb-4 mb-lg-0">
                    <img src="{% static 'assets/img/other/about-2.png' %}" alt="img">
                </div>
            </div>
            <div class="col-lg-6 order-lg-first align-self-center">
                <div class="section-title mb-0 text-center text-lg-start">
                    <h3 class="sub-title">Our History</h3>
                    <h2 class="title">Origins of the restaurant</h2>
                    <p>Sharing knowledge and skills is what we do. With passion. That’s why the Alimentarium organises
                        daily culinary workshops and classes led by qualified chefs. A neque malesuada in tortor eget
                        justo mauris nec dolor. Consequat risus vitae, ac ac et preparation.</p>
                    <p>Nunc quam nibh diam in eget. Tortor amet, eleifend sed viverra ac eu porta netus pulvinar. Quis
                        sem donec pharetra viverra consectetur aliquam, platea egestas. Egestas quis fringilla cursus
                        nullam. Nisl vulputate aliquam odio massa mattis.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- about Area End -->

<!-- about Area Start-->
<section class="about-area pd-top-120 pd-bottom-90">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="thumb">
                    <img src="{% static 'assets/img/other/about.png' %}" alt="img">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="section-title text-center text-lg-start">
                    <h3 class="sub-title">Why choose us</h3>
                    <h2 class="title">Why we are the best</h2>
                    <p>A, blandit euismod ullamcorper vestibulum enim habitasse. Ultrices tincidunt scelerisque elit
                        enim. A neque malesuada in tortor eget justo mauris nec dolor. Consequat risus vitae, ac ac et
                        preparation. He wanted to serve burgers, fries and beverages that tasted .</p>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="single-about-wrap">
                            <img src="{% static 'assets/img/icon/1.png' %}" alt="img">
                            Fresh food
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-about-wrap">
                            <img src="{% static 'assets/img/icon/2.png' %}" alt="img">
                            Fast Delivery
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-about-wrap">
                            <img src="{% static 'assets/img/icon/3.png' %}" alt="img">
                            Quality Maintain
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-about-wrap">
                            <img src="{% static 'assets/img/icon/4.png' %}" alt="img">
                            24/7 Service
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- about Area End -->

<!-- video Area Start-->
<section class="video-area featured-area pd-bottom-150" style="background-image: url(assets/img/other/video.png);">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title text-lg-start text-center">
                    <h3 class="sub-title text-secondary">Why choose us</h3>
                    <h2 class="title text-white">Visit our kitchens to see how we prepare your favorite dish</h2>
                </div>
            </div>
            <div class="col-lg-6 align-self-center text-center">
                <a class="play-btn" href="#"><i class="ri-play-circle-fill"></i></a>
            </div>
        </div>
    </div>
</section>
<!-- video Area End -->

<!-- testimonial Area Start-->
<section class="testimonial-area text-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7 col-md-10">
                <div class="testimonial-slider owl-carousel">
                    <div class="item">
                        <div class="testimonial-wrap">
                            <p>“We have no regrets! I don't know what else to say. It really saves me time and effort.
                                Food is exactly what our business has been lacking”</p>
                            <h3>Julia R. Davis
                            </h3>
                            <h6>Food Bloger</h6>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial-wrap">
                            <p>“We have no regrets! I don't know what else to say. It really saves me time and effort.
                                Food is exactly what our business has been lacking”</p>
                            <h3>Davis J. Rulia
                            </h3>
                            <h6>Food Bloger</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- testimonial Area End -->

<!-- blog Area Start-->
<section class="blog-area pd-bottom-90">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-7">
                <div class="section-title text-center">
                    <h3 class="sub-title">News & Blog</h3>
                    <h2 class="title">Celebrating the awesomeness of food.</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6">
                <div class="single-blog-wrap">
                    <div class="thumb">
                        <img src="{% static 'assets/img/blog/1.png' %}" alt="img">
                    </div>
                    <div class="wrap-details">
                            <span class="cat">
                                <span class="date">
                                    <i class="ri-calendar-todo-fill"></i>July 14, 2021
                                </span>
                                <a href="#" class="tag me-0">
                                    <i class="ri-price-tag-3-fill"></i>Burgar
                                </a>
                            </span>
                        <h5><a href="blog-details.html">Greek yogurt breakfast bowls with toppings</a></h5>
                        <div class="wrap-hover-area">
                            <p> It with just a touch of sauce. saucy riff, more in the style of takeout American Chinese
                                kung pao. The sauce makes it perfect for eating with rice.
                            </p>
                            <a class="link-btn" href="blog-details.html">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single-blog-wrap">
                    <div class="thumb">
                        <img src="{% static 'assets/img/blog/2.png' %}" alt="img">
                    </div>
                    <div class="wrap-details">
                            <span class="cat">
                                <span class="date">
                                    <i class="ri-calendar-todo-fill"></i>July 05, 2021
                                </span>
                                <a href="#" class="tag me-0">
                                    <i class="ri-price-tag-3-fill"></i>Pizza
                                </a>
                            </span>
                        <h5><a href="blog-details.html">Broad beans, tomato, garlic & cheese bruschetta
                        </a></h5>
                        <div class="wrap-hover-area">
                            <p> It with just a touch of sauce. saucy riff, more in the style of takeout American Chinese
                                kung pao. The sauce makes it perfect for eating with rice.
                            </p>
                            <a class="link-btn" href="blog-details.html">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single-blog-wrap">
                    <div class="thumb">
                        <img src="{% static 'assets/img/blog/3.png' %}" alt="img">
                    </div>
                    <div class="wrap-details">
                            <span class="cat">
                                <span class="date">
                                    <i class="ri-calendar-todo-fill"></i>August 14, 2021
                                </span>
                                <a href="#" class="tag me-0">
                                    <i class="ri-price-tag-3-fill"></i>Pizza
                                </a>
                            </span>
                        <h5><a href="blog-details.html">Make authentic Italian margherita pizza at home
                        </a></h5>
                        <div class="wrap-hover-area">
                            <p> It with just a touch of sauce. saucy riff, more in the style of takeout American Chinese
                                kung pao. The sauce makes it perfect for eating with rice.
                            </p>
                            <a class="link-btn" href="blog-details.html">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- blog Area End -->
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block head %}

{% endblock head %}

{% block body %}
<!-- Banner Area Start-->
<section class="banner-area">
    <div class="banner-thumb">
        <img src="{% static 'assets/img/banner/banner.png' %}" alt="img">
    </div>
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 align-self-center">
                <div class="banner-inner text-center">
                    <h3>Do not miss it!</h3>
                    <h1>Pizza tastes better than skinny feels.</h1>
                    <a class="btn btn-secondary" href="shop.html">GET IT NOW</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Area End -->
<!-- testimonial Area Start-->
<section class="testimonial-area text-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7 col-md-10">
                <div class="testimonial-slider owl-carousel">
                    <div class="item">
                        <div class="testimonial-wrap">
                            <p>“We have no regrets! I don't know what else to say. It really saves me time and effort.
                                Food is exactly what our business has been lacking”</p>
                            <h3>Julia R. Davis
                            </h3>
                            <h6>Food Bloger</h6>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial-wrap">
                            <p>“We have no regrets! I don't know what else to say. It really saves me time and effort.
                                Food is exactly what our business has been lacking”</p>
                            <h3>Davis J. Rulia
                            </h3>
                            <h6>Food Bloger</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- testimonial Area End -->
{% endblock body %}

templates/login.html
{% extends "layout.html" %}

{% block body %}

{% include 'includes/breadcrumb.html' %}

{% load crispy_forms_tags %}
<div class="row mb-5 mt-5">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <hr>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load static %}
{% block body %}

{% include 'includes/breadcrumb.html' %}

{% load crispy_forms_tags %}
<div class="row mt-5 mb-5">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <hr>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
</div>

{% endblock body %}


templates/update.html
{% extends "layout.html" %}
{% block body %}

{% include 'includes/breadcrumb.html' %}

{% load crispy_forms_tags %}
<div class="row mb-5 mt-5">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <hr>
            <button type="submit" class="btn btn-danger">Kaydet</button>
        </form>
    </div>
</div>
{% endblock %}